const Images = {
    drone1 : require('./drone1.jpg'),
    drone2 : require('./drone2.png'),
    drone3 : require('./drone3.png'),
    drone : require('./drone.png'),
    profile : require('./profile.jpg'),
    pilot : require('./pilot.jpg'),
    coral : require('./gray.jpg'),
    experience: require('./experience.png'),
    droneIcon: require('./droneIcon.png'),
    certified: require('./certified.png'),
    droneBanner: require('./droneBanner.jpg'),
    droneDelivery: require('./DroneDelivery.png'),
    searchJobs: require('./searchJobs.jpeg'),
    myDrones: require('./myDrones.jpg'),
    learnDrone: require('./learnDrone.jpg'),
    loading: require('../assets/giphy.gif'),
    companyCoral: require('./companyCoral.png'),
    institute: require('./institute.png'),
    calender: require('./calendarOrange.png'),
    agri_survey: require('./agri_survey.jpg'),
    cine_main: require('./cine_Main.jpg'),
    cinematography: require('./cinematography.jpg'),
    
}
export default Images;