import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { AntDesign } from '@expo/vector-icons';
import { ScrollView } from 'react-native-gesture-handler';

export default function TermsAndConditions({navigation}) {
  return (
    <ScrollView>
            <View style={{ alignItems:'center', padding:15, backgroundColor:'coral', elevation:15, width:'100%'}}>
              <TouchableOpacity style={styles.closeButton} onPress={() => {navigation.navigate("Home")}}>
                <AntDesign name="close" size={28} color="white" />
              </TouchableOpacity>
              <Text style={{color:'white', fontWeight:'bold', fontSize:22}}>Terms and Condition</Text>
            </View>
    <View style={styles.container}>     

        <Text style={styles.heading}>DronesWala End user Terms and Conditions</Text>
        <Text style={styles.normalText}>In terms of Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.</Text>
        <Text style={styles.normalText}>The DronesWala internet resource 'marketplace' / DronesWala Mobile Application / services (herein after referred to as the "Platform" is owned by DronesWala Technologies Private Limited, having its registered office at 175 & 176, Dollors Colony, JP Nagar, Bannerghatta Main Road, Bengaluru – 560 076 (hereinafter referred to as "Company/DronesWala"). This document in its present form is the property of DronesWala Technologies Private Limited and shall belong to DronesWala Technologies Private Limited, its subsidiaries and assigns as may be created from time to time.</Text>
        
        <Text style={styles.heading}>GENERAL</Text>
        <Text style={styles.normalText}>By accepting these Terms, you are entering into a legally binding Agreement ("Agreement") with us. This Agreement consists of the following terms and conditions (hereinafter the "General Terms") and terms and conditions specific to use of individual Services (hereinafter the "Service Specific Terms"). The General Terms and Service Specific Terms are collectively referred to as the "Terms". In the event of a conflict between the General Terms and Service Specific Terms, the Service Specific Terms shall prevail. These Terms, along with the others found on our Platform, include our policy for acceptable use of the Platform, its content, the content posted on the Platform, your rights, your obligations, as well as restrictions regarding your use of the Platform. When you access, browse or use the Platform, you accept, without limitation or qualification, the terms and conditions set forth herein. When you access or use any of the Services, you will be subject to the rules, regulations, policies and all applicable terms and conditions which shall be deemed to be incorporated into and be a part and parcel of these Terms. When you access any sub-site or any other mobile application (whether belonging to an 'associate' of the company or otherwise) through this Platform, such sub-site or mobile application may have its own terms and conditions, which are specific to there to.</Text>

        <Text style={styles.heading}>DEFINITIONS</Text>
        <Text style={styles.normalText}>"Account" shall mean the account created by the Customer on the Platform for availing the Services provided by DronesWala. </Text>
        <Text style={styles.normalText}>"Applicable Laws" shall mean any statute, law, regulation, ordinance, rule, judgment, notification, rule of common law, order, decree, by-law, government approval, directive, guideline, or any interpretation, policy or administration having the force of law in India, by any authority having jurisdiction over the matter in question, whether in effect as of the date of this Agreement or thereafter, and the word "Laws" shall be construed accordingly.</Text>
        <Text style={styles.normalText}>"Application" shall mean the mobile application "DronesWala" as updated by DronesWala Technologies from time to time.</Text>
        <Text style={styles.normalText}>"Content" refers to any text, image, graphic, video, audio, or all forms of data which are made available on the Platform.</Text>
        <Text style={styles.normalText}>"Customer / You / User" shall mean the natural person who has gained access to the Platform by providing Registration Data while registering for Services.</Text>
        <Text style={styles.normalText}>"Insurer" shall have the same meaning as set forth in The Insurance Act, 1938, as amended from time to time.</Text>
        <Text style={styles.normalText}>"Intellectual Property Rights" refers to all intellectual property rights and all analogous rights subsisting under the laws of each and every jurisdiction throughout the world and intellectual property for the full term of the rights concerned and including all extensions and renewals of such rights, whether or not such rights are registered or capable of registration, including, without limitation, copyrights, trademarks, trade names, service marks, service names, patents, designs and all other proprietary rights of whatsoever description whether or not protected and whether or not capable of protection.</Text>
        <Text style={styles.normalText}>"Platform" shall mean the online marketplace accessible at www.DronesWala.com/marketplace.html, the DronesWala mobile application, as well as the services made available by DronesWala.</Text>
        <Text style={styles.normalText}>"Registration Data" shall mean the mandatory and optional data that is submitted by Users to browse the Platform and/or avail the Services, which includes data related to your drones.</Text>
        <Text style={styles.normalText}>"Insurance" shall mean the insurance availed by the User from the Insurer, facilitated through the Platform.</Text>
        <Text style={styles.normalText}>"Insurance Fee" shall mean such amount in Indian Rupees, which is reflected on the Platform, as the fee for availing the Insurance.</Text>
        <Text style={styles.normalText}>"Service(s)" shall mean the facilitation of insurance service by DronesWala through the Platform as well as the provision of an online marketplace</Text>
        <Text style={styles.normalText}>"Terms", "Terms and conditions", "Policy", etc., shall mean the entire Terms of Use and all parallel policies that apply for the use of our Platform or availing our Services. </Text>
        <Text style={styles.normalText}>"Your Content" refers to any content submitted by way of registration or in connection with use of the Platform or for availing Services. </Text>
        <Text style={styles.normalText}>"DronesWala" or "us" or "we" or "our" shall mean DronesWala Technologies Private Limited.</Text>
    
        <Text style={styles.heading}>PRIVACY POLICY</Text>
        <Text style={styles.normalText}>Our General Privacy Policy is separately available on the Platform and can be perused by you at your convenience here: www.DronesWala.com/privacy-policy.html.</Text>
        
        <Text style={styles.heading}>ELIGIBILITY</Text>
        <Text style={styles.normalText}>You must be of legal age to enter into a binding agreement in order to accept the Terms.</Text>
        <Text style={styles.normalText}>Without limitation to the foregoing, in the event you are barred from undertaking legally binding obligations under the Indian Contract Act, 1872, or are for any reason, unable to provide 'Consent' as per the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011, you are not eligible to register for, use or avail the services available on the Platform. Not withstanding the aforementioned, the minimum age of Users must be 18 years</Text>

        <Text style={styles.heading}>REGISTRATION AS A USER</Text>
        <Text style={styles.normalText}>To become a registered User, you must be eligible, and will be required to provide Registration Data. You represent and warrant that all information you supply to us, about yourself, and others, including Registration Data, is true and accurate.</Text>
        <Text style={styles.normalText}>If you provide any information that is untrue, inaccurate, out of date or incomplete (or becomes untrue, inaccurate, out of date or incomplete), or we have reasonable grounds to suspect that the information provided by you is untrue, inaccurate, out of date or incomplete, we may, in our sole discretion, discontinue the provision of the Services to you or discontinue your access to the Platform by suspending or terminating your Account.</Text>
        <Text style={styles.normalText}>By providing Registration Data, you agree to undergo a Registration Data verification process which may include you providing One Time Password / OTP to verify your mobile number, and verifying your e-mail id using the verification link sent to the e-mail address you provide as part of Registration Data.</Text>
        <Text style={styles.normalText}>It is hereby reiterated that all data you provided, including without limitation, Registration Data, shall be subject to the terms set forth in our Privacy Policy, and you represent and warrant that you have the absolute right and authority to provide such data.</Text>
        <Text style={styles.normalText}>In the event you find any content on the website which you deem is unlawful, libellous, defamatory, obscene, pornographic, indecent, lewd, suggestive, harassing, threatening, invasive of privacy or publicity rights, abusive, inflammatory, fraudulent or otherwise objectionable, against any religious beliefs, spam, potentially infringing or is not authorized by the intellectual property rights owner or is violative of any applicable law, you are requested to report such content to hello@DronesWala.com. On receiving such report, the company reserves the right to investigate and/or take such action as the company may deem appropriate.</Text>

    </View>
    </ScrollView>
    )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f0f0f0aa',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical:25,
    marginHorizontal:15,
  },
  heading: {
    fontSize:18,
    fontWeight:'bold',
    marginBottom:11,
    marginTop:5,
    textAlign:'center'

  },
  normalText: {
    fontSize:14,
    marginBottom:7,
  },
  closeButton: {
    position: 'absolute',
    top: 15,
    left: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
